name: Java CI + Docker + Kubernetes Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Build Spring Boot JAR
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4️⃣ SonarCloud Scan (after build, before Docker)
      - name: SonarCloud Scan
        run: mvn sonar:sonar \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 5️⃣ Build & Push Docker Image (VERSIONED)
      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sharvilvajja/spring-boot-cicd-pipeline
          tags: v${{ github.run_number }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}